---
title: "Fivethirtyeight Graphic Remake"
author: "Simone Chu"
date: "2/11/2019"
output: html_document
---

```{r setup, include=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

```{r, echo = FALSE, message=FALSE, warning=FALSE}
library(fivethirtyeight)
library(tidyverse)
library(ggthemes)
data("congress_age")
    # Loading relevant packages. 

congress_age %>%
  mutate(year = 2*congress + 1787) %>%
    # This gives me an easier-to-interpret 'year' column, instead of going by 'congress'.
  filter(incumbent == FALSE, party %in% c("D", "R")) %>% 
    # This lets me get the data of only new members of Congress. Also, since the 538 graph only focuses on Republicans and Democrats, this helps me filter out any members of Congress affiliated with political parties outside of those two. 
  group_by(year, party) %>% 
    # The 538 graph has separate lines for each party, and it makes sense to group by year (otherwise, there would only be one average age for the whole graph!). 
  mutate(avg_age = mean(age)) %>%
    # This gives me the 'avg_age' each year to graph! 
ggplot(congress_age, mapping = aes(x = year, y = avg_age, color = party)) + 
  geom_line(size = 1, show.legend = FALSE) +
    # The original fivethirtyeight graph doesn't display the legend, so I'll hide it here. 
  scale_x_continuous(breaks = seq(1950, 2010, by = 10),
                     label = c("1950", "'60", "'70", "'80", "'90", "2000", "'10")) +
    # The original fivethirtyeight graph has tick marks at each decade, so I recreated it by inserting breaks every 10 years and labeling them. 
  scale_y_continuous(breaks = seq(40, 60, by = 5),
    label = c("40", "45", "50", "55", "60 yrs")) +
    # This lets me set the scale of the y-axis to match the original 538 graph, since the default has an upper limit of 55 rather than 60. 
  expand_limits(y=c(40, 60)) +
    # Without expand_limits, the graph only shows breaks for ages 45, 50, and 55; adding this in ensures that it looks more like the original graph, by telling it to leave the breaks for age 40 and age 60 instead of leaving them out. 
  ggtitle("Average Age of New Members of Congress") +
    # Added to replicate the title! 
  labs(subtitle = "Rolling two-term average at start of term, 1949-2013", caption = "SOURCE: GOVTRACK, THE NEW YORK TIMES, SUNLIGHT FOUNDATION") + 
    # Added to replicate the subtitle and caption. 
  theme_fivethirtyeight() + 
    # I used the fivethirtyeight theme to try to make the graph look more like the original. 
  theme(axis.title.x=element_blank(), axis.title.y=element_blank()) + 
    # The original 538 graph doesn't have the axis titles displayed, so I added this to avoid displaying "year" and "avg_age" on the axes. 
  scale_color_manual(values=c("#008FD5", "#FF2700")) + 
    # For some reason, it was showing Democrats with red and Republicans with blue, which is not what the original fivethirtyeight graph displayed. I set the colors manually, using hexcodes from here (https://rdrr.io/cran/ggthemes/man/fivethirtyeight_pal.html) to match the colors Fivethirtyeight usually uses. 
  annotate("text", x = 2005, y = 54.5, label = "Democrats", color = "#008FD5") +
  annotate("text", x = 1965.7, y = 48.5, label = "Republicans", color = "#FF2700")
    # I wanted to make sure that the color of the labels for each matched the line colors, so I used the hex codes again. Positioning was done through trial and error. 
```
